
package com.shop.dreampizza.service.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.shop.dreampizza.service.bean.Order;
import com.shop.dreampizza.service.bean.OrderArray;
import com.shop.dreampizza.service.order.net.ObjectFactory;
import com.shop.dreampizza.service.order.net.IntArray;
import com.shop.dreampizza.service.pizza.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://service.dreampizza.shop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class,
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @return
     *     returns com.shop.dreampizza.service.OrderArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.dreampizza.shop.com/OrderService/getAllOrdersRequest", output = "http://service.dreampizza.shop.com/OrderService/getAllOrdersResponse")
    public OrderArray getAllOrders();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.shop.dreampizza.service.Order
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.dreampizza.shop.com/OrderService/getOrderByIdRequest", output = "http://service.dreampizza.shop.com/OrderService/getOrderByIdResponse")
    public Order getOrderById(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.dreampizza.shop.com/OrderService/makeOrderRequest", output = "http://service.dreampizza.shop.com/OrderService/makeOrderResponse")
    public void makeOrder(
            @WebParam(name = "arg0", partName = "arg0")
                    IntArray arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    IntArray arg1);

}
