package com.shop.dreampizza.service.order.impl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "OrderServiceImplService", targetNamespace = "http://impl.service.dreampizza.shop.com/", wsdlLocation = "http://localhost:8081/PizzaShop/orderService?wsdl")
public class OrderServiceImplServiceShop2
        extends Service
{
    private final static URL ORDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ORDERSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.dreampizza.shop.com/", "OrderServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/PizzaShop/orderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ORDERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OrderServiceImplServiceShop2() {
        super(__getWsdlLocation(), ORDERSERVICEIMPLSERVICE_QNAME);
    }

    public OrderServiceImplServiceShop2(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrderServiceImplServiceShop2(URL wsdlLocation) {
        super(wsdlLocation, ORDERSERVICEIMPLSERVICE_QNAME);
    }

    public OrderServiceImplServiceShop2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrderServiceImplServiceShop2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceImplServiceShop2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort() {
        return super.getPort(new QName("http://impl.service.dreampizza.shop.com/", "OrderServiceImplPort"), OrderService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.dreampizza.shop.com/", "OrderServiceImplPort"), OrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ORDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
