
package com.shop.dreampizza.service.pizza.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PizzaServiceImplService", targetNamespace = "http://impl.service.dreampizza.shop.com/", wsdlLocation = "http://localhost:8080/PizzaShop/pizzaService?wsdl")
public class PizzaServiceImplServiceShop1
    extends Service
{

    private final static URL PIZZASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PIZZASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PIZZASERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.dreampizza.shop.com/", "PizzaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PizzaShop/pizzaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIZZASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PIZZASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PizzaServiceImplServiceShop1() {
        super(__getWsdlLocation(), PIZZASERVICEIMPLSERVICE_QNAME);
    }

    public PizzaServiceImplServiceShop1(WebServiceFeature... features) {
        super(__getWsdlLocation(), PIZZASERVICEIMPLSERVICE_QNAME, features);
    }

    public PizzaServiceImplServiceShop1(URL wsdlLocation) {
        super(wsdlLocation, PIZZASERVICEIMPLSERVICE_QNAME);
    }

    public PizzaServiceImplServiceShop1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PIZZASERVICEIMPLSERVICE_QNAME, features);
    }

    public PizzaServiceImplServiceShop1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaServiceImplServiceShop1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PizzaService
     */
    @WebEndpoint(name = "PizzaServiceImplPort")
    public PizzaService getPizzaServiceImplPort() {
        return super.getPort(new QName("http://impl.service.dreampizza.shop.com/", "PizzaServiceImplPort"), PizzaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaService
     */
    @WebEndpoint(name = "PizzaServiceImplPort")
    public PizzaService getPizzaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.dreampizza.shop.com/", "PizzaServiceImplPort"), PizzaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIZZASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PIZZASERVICEIMPLSERVICE_EXCEPTION;
        }
        return PIZZASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
