
package com.shop.dreampizza.service.pizza.impl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.shop.dreampizza.service.pizza.ObjectFactory;
import com.shop.dreampizza.service.pizza.PizzaArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PizzaService", targetNamespace = "http://service.dreampizza.shop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PizzaService {


    /**
     * 
     * @return
     *     returns com.shop.dreampizza.service.PizzaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.dreampizza.shop.com/PizzaService/getAllPizzasRequest", output = "http://service.dreampizza.shop.com/PizzaService/getAllPizzasResponse")
    public PizzaArray getAllPizzas();

}
